# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dlmnomPP <- function(Y_wp, theta_c) {
    .Call(`_mills_dlmnomPP`, Y_wp, theta_c)
}

dlmnomPPw <- function(Y_wp, theta_c, w) {
    .Call(`_mills_dlmnomPPw`, Y_wp, theta_c, w)
}

dlmnom_sep <- function(Y_wp, theta_c) {
    .Call(`_mills_dlmnom_sep`, Y_wp, theta_c)
}

